### ISSUE TITLE
Unable to save the file - encryption key

### ISSUE THREAD

**Issue by shanka12** [aminyazdanpanah/PHP-FFmpeg-video-streaming#72]
After adding ->encryption($save_to, $url) , I got below error;

`ERROR: Unable to save the file {"exception":"[object] (Streaming\\Exception\\RuntimeException(code: 0): Unable to save the file at /vendor/vendor/aminyazdanpanah/php-ffmpeg-video-streaming/src/File.php:68)

[stacktrace]
#0 //vendor/aminyazdanpanah/php-ffmpeg-video-streaming/src/HLSKeyInfo.php(77): Streaming\\File::put()
#1 /vendor/aminyazdanpanah/php-ffmpeg-video-streaming/src/HLSKeyInfo.php(111): Streaming\\HLSKeyInfo->createKey()
#2 /vendor/aminyazdanpanah/php-ffmpeg-video-streaming/src/HLSKeyInfo.php(120): Streaming\\HLSKeyInfo->generate()
#3 //vendor/aminyazdanpanah/php-ffmpeg-video-streaming/src/HLS.php(138): Streaming\\HLSKeyInfo->__toString()
`

```
$save_to = 'path';
$url = 'path/enc.key';
 $reps = new AutoReps($video, $format, [360, 480, 720, 1080]);
$video->hls()
            ->encryption($save_to, $url)
            ->setFormat($format)
            ->setHlsTime(5) // Set Hls Time. Default value is 10
            ->setHlsAllowCache(false)
            ->addRepresentations($reps->getCalculatedReps())
            ->save($save_path);
```

**Comment by shanka12** [comment]
it was issue with save to path . I fixed
